default: &default
  host: localhost
  port: 3001
  user: root
  password: root
  encoding: unicode
  adapter: postgresql  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_api_development

test:
  <<: *default
  database: ecommerce_api_test

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
